name: Create Anki release with multiple jobs
on:
  workflow_dispatch:
    inputs:
      from:
        description: Language of words from given .txt file
        options:
        - es
        - en
        required: true
        type: choice
      numberOfWords:
        description: How many Cards/Words your Anki Deck should have (Whole Number!)
          Write 0 to go through the whole .txt file.
        required: true
        type: string
      textfilename:
        description: Name of your .txt file
        required: true
        type: string
      to:
        description: Language to which should be translated to
        options:
        - en
        - es
        required: true
        type: choice
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install wheel

        pip install -r requirements.txt

        '
    - name: build Anki Deck most-common-spanish-words.txt
      run: 'python main.py lists/most-common-spanish-words.txt es en 10000

        '
    - name: build Anki Deck most-common-spanish-words-v5.txt
      run: 'python main.py lists/most-common-spanish-words-v5.txt es en 10000

        '
    - name: build Anki Deck es_50k.txt
      run: 'python main.py lists/es_50k.txt es en 10000

        '
    - name: build Anki Deck 10000mostusedspanish.txt
      run: 'python main.py lists/10000mostusedspanish.txt es en 10000

        '
    - name: Upload Anki Deck
      uses: actions/upload-artifact@v3.0.0
      with:
        name: release
        path: GeneratedAnkiDeck.apkg
        retention-days: 90
    - name: Upload not_translated
      uses: actions/upload-artifact@v3.0.0
      with:
        name: not_translated
        path: not_translated.txt
        retention-days: 90
