# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: single file, Git push

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'Path and name of your .txt file (eg. "path/path2/file" not "path/path2/name.txt"'
        required: true
        type: string
      from:
        description: 'Language of words from given .txt file in short form (see Readme)'
        required: true
        type: string
      to:
        description: 'Language to which should be translated to in short form (see Readme)'
        required: true
        type: string
      numberOfWords:
        description: 'How many Cards/Words your Anki Deck should have (Whole Number!) 
        Write 0 to go through the whole .txt file.
        There is a 6h Github Action time limit!!! 
        So max. Word (in Github Actions) are ca. 20000'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
    - name: build Anki Deck
      run: |
        python main.py  ${{ github.event.inputs.file }} ${{ github.event.inputs.from }} ${{ github.event.inputs.to }} ${{ github.event.inputs.numberOfWords }}
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Updated via Actions" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        branch: ${{ github.ref }}
